name: Build Android APK

on:
  push:
    branches: [ "main" ] # mude para master se sua branch principal tiver esse nome

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Permissao no Gradlew
      run: chmod +x gradlew
      
    - name: Compilar APK
      run: ./gradlew assembleDebug

    - name: Enviar APK Pronto
      uses: actions/upload-artifact@v4
      with:
        name: meu-app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
